"""create users

Revision ID: 58e6b4de705b
Revises: 8a2bfb00d8d0
Create Date: 2022-07-15 01:13:10.444164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e6b4de705b'
down_revision = '8a2bfb00d8d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
