"""create users

Revision ID: 898d1c198713
Revises: f6af05d78e3e
Create Date: 2022-07-15 00:41:07.534578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898d1c198713'
down_revision = 'f6af05d78e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('btc_wallet', sa.String(length=40), nullable=True))
    op.add_column('users', sa.Column('warns', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'warns')
    op.drop_column('users', 'btc_wallet')
    op.drop_column('users', 'balance')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
