"""create users

Revision ID: 8a2bfb00d8d0
Revises: 97acfa7d4cc4
Create Date: 2022-07-15 01:08:41.727990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2bfb00d8d0'
down_revision = '97acfa7d4cc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
