"""create users

Revision ID: 97acfa7d4cc4
Revises: 898d1c198713
Create Date: 2022-07-15 01:05:47.547651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97acfa7d4cc4'
down_revision = '898d1c198713'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
